slam_toolbox:
  ros__parameters:
    mode: "mapping"
    map_frame: "robot2/map"
    base_frame: "robot2/base_footprint"
    odom_frame: "robot2/odom"
    scan_topic: "robot2/scan"
    map_topic: "robot2/map"
    resolution: 0.05
    max_laser_range: 3.5
    transform_publish_period: 0.05

