slam_toolbox:
  ros__parameters:
    mode: "mapping"
    map_frame: "robot1/map"
    base_frame: "robot1/base_footprint"
    odom_frame: "robot1/odom"
    scan_topic: "scan"
    map_topic: "local_map"
    resolution: 0.05
    max_laser_range: 3.5
    minimum_time_interval: 0.5
